<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>FAT32Explorer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../FAT32Explorer.Nucleo/FAT32Explorer.Nucleo.csproj" />
  </ItemGroup>
</Project>
